# Generated by Django 5.1.6 on 2025-04-02 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('discription', models.TextField(max_length=5000)),
                ('lastDate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
