# Generated by Django 5.1.6 on 2025-04-05 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createdAt',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
