# Generated by Django 5.1.6 on 2025-04-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(default='none@gmail.com', max_length=254),
        ),
    ]
